# **ML Lab - Support Vector Machine**
Urlana Suresh Kumar - 22071A6662

# SVM Classification on Iris Dataset
This notebook demonstrates how to classify the Iris dataset using Support Vector Classification (SVC) with different kernel types.

In [6]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import pandas as pd

## Step 1: Loading and Preparing Dataset


In [7]:
from sklearn.datasets import load_iris
iris = load_iris()

print(iris.data[:5], "\n")
X = iris.data
print(type(X))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]] 

<class 'numpy.ndarray'>


In [8]:
#Target Data
print("\n", iris.target, "\n")
y = iris.target


 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2] 



## Step 2: Splitting the Dataset & Feature Scaling


In [9]:
# Splitting DataSet
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=82)

In [10]:
## Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Step 3:SVC With Linear Kernel

In [11]:
## SVC with Kernel
from sklearn.svm import SVC
svcclassifier = SVC(kernel='linear', random_state=0)
svcclassifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

### 1.Test Set Result

In [12]:
y_pred = svcclassifier.predict(X_test)
print("\n", y_pred, "\n")


 [2 2 0 0 0 2 1 1 2 1 1 2 0 0 0 0 2 1 0 1 0 2 0 2 2 1 2 0 2 1] 



### 2.Comparing Actual and Predicted Values (Linear Kernel

In [13]:
y_compare = np.vstack((y_test, y_pred)).T
y_compare[:5, :]

array([[2, 2],
       [2, 2],
       [0, 0],
       [0, 0],
       [0, 0]])

### 3.Confusion Matrix (Linear Kernel)

In [14]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("\n", cm, "\n")


 [[11  0  0]
 [ 0  8  1]
 [ 0  0 10]] 



### 4.Calculating Accuracy (Linear Kernel)

In [15]:
a = cm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred += cm[row, c]
        else:
            falsePred += cm[row, c]
print('Correct predictions: \n', corrPred)
print('False predictions \n', falsePred)
kernelLinearAccuracy = corrPred / (cm.sum())
print('Accuracy of the SVC Classification is: \n', kernelLinearAccuracy)

Correct predictions: 
 29
False predictions 
 1
Accuracy of the SVC Classification is: 
 0.9666666666666667


## Step 4:SVC with Polynomial Kernel

In [16]:
svcclassifier = SVC(kernel='poly', random_state=0)
svcclassifier.fit(X_train, y_train)

SVC(kernel='poly', random_state=0)

### 1.Predicting Test Set Results (Polynomial Kernel)

In [17]:
y_pred = svcclassifier.predict(X_test)
print("\n", y_pred, "\n")


 [2 2 0 0 0 1 1 1 1 1 1 1 0 0 0 0 2 1 0 1 0 2 0 2 2 1 2 0 2 1] 



### Comparing Actual and Predicted Values (Polynomial Kernel)

In [18]:
y_compare = np.vstack((y_test, y_pred)).T
y_compare[:5, :]

array([[2, 2],
       [2, 2],
       [0, 0],
       [0, 0],
       [0, 0]])

### 3.Confusion Matrix (Polynomial Kernel)



In [19]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[11  0  0]
 [ 0  9  0]
 [ 0  2  8]]


### 4.Calculating Accuracy (Polynomial Kernel)

In [20]:
a = cm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred += cm[row, c]
        else:
            falsePred += cm[row, c]
print('Correct predictions: \n', corrPred)
print('False predictions \n', falsePred)
kernelPolyAccuracy = corrPred / (cm.sum())
print('Accuracy of the SVC Classification is: \n', kernelPolyAccuracy)

Correct predictions: 
 28
False predictions 
 2
Accuracy of the SVC Classification is: 
 0.9333333333333333


## Step 5:SVC with RBF Kernel

In [21]:
svcclassifier = SVC(kernel='rbf', random_state=0)
svcclassifier.fit(X_train, y_train)

SVC(random_state=0)

### 1.Predicting Test Set Results (RBF Kernel)

In [22]:
y_pred = svcclassifier.predict(X_test)
print("\n", y_pred, "\n")


 [2 2 0 0 0 2 1 1 1 1 1 2 0 0 0 0 2 1 0 1 0 2 0 2 2 1 2 0 2 1] 



### 2.Comparing Actual and Predicted Values (RBF Kernel)

In [23]:
y_compare = np.vstack((y_test, y_pred)).T
y_compare[:5, :]

array([[2, 2],
       [2, 2],
       [0, 0],
       [0, 0],
       [0, 0]])

### 3.Confusion Matrix (RBF Kernel)

In [24]:
cm = confusion_matrix(y_test, y_pred)
print("\n", cm, "\n")


 [[11  0  0]
 [ 0  8  1]
 [ 0  1  9]] 



### 4.Calculating Accuracy (RBF Kernel)

In [25]:
a = cm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred += cm[row, c]
        else:
            falsePred += cm[row, c]
print('Correct predictions: \n', corrPred)
print('False predictions \n', falsePred)
kernelRbfAccuracy = corrPred / (cm.sum())
print('Accuracy of the SVC Classification is: \n', kernelRbfAccuracy)

Correct predictions: 
 28
False predictions 
 2
Accuracy of the SVC Classification is: 
 0.9333333333333333


## Step 6:SVC with Sigmoid Kernel


In [26]:
svcclassifier = SVC(kernel='sigmoid', random_state=0)
svcclassifier.fit(X_train, y_train)

SVC(kernel='sigmoid', random_state=0)

### 1.Predicting Test Set Results (Sigmoid Kernel)

In [27]:
y_pred = svcclassifier.predict(X_test)
print("\n", y_pred, "\n")


 [2 2 0 0 0 2 1 2 2 2 2 2 0 0 0 0 2 2 0 1 0 2 0 2 2 1 2 0 2 1] 



### 2.Comparing Actual and Predicted Values (Sigmoid Kernel)

In [28]:
y_compare = np.vstack((y_test, y_pred)).T
y_compare[:5, :]

array([[2, 2],
       [2, 2],
       [0, 0],
       [0, 0],
       [0, 0]])

### 3.Confusion Matrix (Sigmoid Kernel)

In [29]:
cm = confusion_matrix(y_test, y_pred)
print("\n", cm, "\n")


 [[11  0  0]
 [ 0  4  5]
 [ 0  0 10]] 



### 4.Calculating Accuracy (Sigmoid Kernel)

In [30]:
a = cm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred += cm[row, c]
        else:
            falsePred += cm[row, c]
print('Correct predictions: \n', corrPred)
print('False predictions \n', falsePred)
kernelSigmoidAccuracy = corrPred / (cm.sum())

Correct predictions: 
 25
False predictions 
 5


# Summary of Accuracies

In [33]:
print('Accuracy of SVC classification with different kernels are:\n')
print('Accuracy of the SVC Classification with Linear kernel: \t\t', kernelLinearAccuracy)
print('Accuracy of the SVC Classification with Polynomial kernel: \t', kernelPolyAccuracy)
print('Accuracy of the SVC Classification with RBF kernel: \t\t', kernelRbfAccuracy)
print('Accuracy of the SVC Classification with Sigmoid kernel: \t', kernelSigmoidAccuracy)

Accuracy of SVC classification with different kernels are:

Accuracy of the SVC Classification with Linear kernel: 		 0.9666666666666667
Accuracy of the SVC Classification with Polynomial kernel: 	 0.9333333333333333
Accuracy of the SVC Classification with RBF kernel: 		 0.9333333333333333
Accuracy of the SVC Classification with Sigmoid kernel: 	 0.8333333333333334
